tasks:
  - name: make
    before: >
      sudo apt-get update &&
      sudo apt-get install -y wget apt-transport-https software-properties-common &&
      sudo wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb" &&
      sudo dpkg -i packages-microsoft-prod.deb &&
      sudo apt-get update &&
      sudo apt-get install -y powershell
    init: make
